iTalantaAcademy-kakuma-1/home

vocabulary/JS_Vocab_Contribution/achiek.md
- it is a string method that is used to remove whitespace characters from the end of a string.
- method removes whitespace from the beginning of a string.
-  method removes the last element from an array and returns that element.
=> achiek's Js vocabuaries

vocabulary/JS_Vocab_Contribution/Elie.md
=> :accept: Or Check it

vocabulary/JS_Vocab_Contribution/abriJS-Vocabulary.md
=> completed my string vocabularies

.vscode/settings.json, vocabulary/JS_Vocab_Contribution/faiso.md
=> Javascript Vocab

vocabulary/JS_Vocab_Contribution/Samuel.md
=> Update javascript vocabularies

vocabulary/JS_Vocab_Contribution/aljabana.md
=> Javascript vocabulary

vocabulary/JS_Vocab_Contribution/Lotiang.md
=> :art: contributing to java_vocab

vocabulary/debugging-vocabularies/AHMED.md
=> ahmed.debugging/vocabulary

vocabulary/debugging-vocabularies/babikir.md
=> 👍;package.debugging

vocabulary/debugging-vocabularies/lotiang.md
=> :art: update.debugging.vocab

vocabulary/debugging-vocabularies/Dessai-Kibeho.md
DEBUGGER
Programming code might contain syntax errors, or logical errors.
Many of these errors are difficult to diagnose.
Often, when programming code contains errors, 
nothing will happen. There are no error messages, and you will get no indications where to search for errors.
=> "Debugger " with Console.log( By Kambale Kibeho

vocabulary/debugging-vocabularies/Aloise.md
=> Erick  daily report

vocabulary/debugging-vocabularies/aljabana.md
=> 👌vocab of uncaught reference error

vocabulary/debugging-vocabularies/paul.md
=> :art: update debugging voc.md

vocabulary/Achieko.md, vocabulary/debugging-vocabularies/Achieko.md
=> debugging update

vocabulary/debugging-vocabularies/fatumoshukri.md
=> add debugging vocab

vocabulary/debugging-vocabularies/AbriYusif.md
=> Completed JavaScript debugging vocabularies

vocabulary/debugging-vocabularies/faiso.md
=> Vocablulary-Hoisting

vocabulary/JS_Vocab_Contribution/fatma.md
=> shukri js vocabulary

snippets/index.html, snippets/script.js, snippets/styles.css
=> Achiek-snippets

.history/snippets/welcome-to-js/Mahdi-snippet-js/mahdi_20220217000356.html, .history/snippets/welcome-to-js/Mahdi-snippet-js/script_20220217000420.js, .history/snippets/welcome-to-js/Mahdi-snippet-js/style_20220217000423.css, snippets/welcome-to-js/Mahdi-snippet-js/mahdi.html, snippets/welcome-to-js/Mahdi-snippet-js/script.js, snippets/welcome-to-js/Mahdi-snippet-js/style.css
=> :+1: this is Mahdi's contributions

snippets/welcome-to-js/christyochala/index.html, snippets/welcome-to-js/christyochala/script.js, vocabulary/JS_Vocab_Contribution/ochalla.md
=> committing my snippet js

vocabulary/JS_Vocab_Contribution/paul.md
=> Paulcontribute voc

snippets/welcome-to-js/shukri-Ibrahim/index.html, snippets/welcome-to-js/shukri-Ibrahim/script.js, snippets/welcome-to-js/shukri-Ibrahim/style.css
=> add js snippet

.vscode/settings.json, snippets/welcome-to-js/aljabana/index.html, snippets/welcome-to-js/aljabana/script.js, snippets/welcome-to-js/aljabana/style.css
=> added javascript vocabulary

snippets/welcome-to-js/Abri/index.html, snippets/welcome-to-js/Abri/script.js, snippets/welcome-to-js/Abri/style.css
=> Abri welcome to js snippets

snippets/welcome-to-js/Lotiang/index.html, snippets/welcome-to-js/Lotiang/index.js, snippets/welcome-to-js/Lotiang/style.css
=> :art: update.snipet

snippets/welcome-to-js/Franco/index.html, snippets/welcome-to-js/Franco/index.js, vocabulary/JS_Vocab_Contribution/franco.md
=> :file how to read codes

vocabulary/JS_Vocab_Contribution/chuol.md
=> 💻💻 javascript vocabularies

vocabulary/JS_Vocab_Contribution/MAhdi'scont.md
=> :art:  java-script commite
